name: BIGGIS23
channels:
  - conda-forge
dependencies:
  - python=3.9
  - affine
  - asyncssh
  - boto3
  - descartes
  - fiona
  - geojson
  - geopandas
  - geopy
  - h3-py
  - ipyleaflet
  - jupyter
  - matplotlib
  - numpy
  - osmnx
  - pandas
  - pillow
  - pint
  - psycopg2
  - pyproj
  - pytest
  - pyrosm
  - pygeos
  - rasterio
  - requests
  - rtree
  - s3fs
  - shapely
  - yaml
  - pip
  - pip:
    - fastparquet
    - gdown
    - pyarrow
    - python-geohash
    - smopy
    - s2
    - s2sphere
    - trackintel
